name: Deploy Pages & Build APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # 网页自动部署
  deploy-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          force_orphan: true

  # APK 打包
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate APK with PWABuilder Action
        uses: pwabuilder/github-action@v1
        with:
          platform: android
          output-path: ./output

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MyApp
          path: ./output/*.apk